name = "bluechat-sync"
main = "worker.js"
compatibility_date = "2024-09-23"
workers_dev = true

kv_namespaces = [
  { binding = "BLUECHAT_KV", id = "23083394123342c0864cbcb2662a17fe" }
]

[observability]
enabled = true
